name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Get current tag.
      - name: Get tag.
        id: tag
        run: |
          CURRENT_VERSION="$(printf %s $(cat version.md))"
          echo "::set-output name=current_version::${CURRENT_VERSION}"

      # Update corresponding major and minor tag.
      # e.g. Update v1 and v1.2 when releasing v1.2.3
      - uses: haya14busa/action-update-semver@v1
        with:
          tag: ${{ steps.tag.outputs.current_version }}

      # Update stable tag.
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "stable"
          message: "release: stable"
          force_push_tag: true
